server:
  port: 8191
spring:
    cloud:
        config:
            server:
                git:
                    search-paths:
                    - '*service'
                    uri: "https://github.com/heislertecreator/spring-cloud-config"
                    
